# Generated by Django 6.1.1 on 2026-09-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='local_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='local_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
